# Record to query for AKD/S data
recordName = "_akds.example.com"

# Public key to verify AKDS signatures against
pubkey = """
----- BEGIN PGP PUBLIC KEY BLOCK -----
...
----- END PGP PUBLIC KEY BLOCK -----
"""

# Whether to accept data from an AKDS record if it fails verification
# Missing signatures on AKDS records will always produce an error
acceptUnverified = false

# URL to pull keys from
# Note that the response is pulled as-is and will not be verified, unlike AKDS
url = "https://example.com/keys"

# Whether to allow fallback to pulling keys from URL if AKD/S fails
allowUrlFallback = true

# Whether to overwrite authorized_keys with AKD/S results
overwriteAuthorizedKeys = false

# Path to authorized_keys
# Relative paths are relative to this config file
# Only applies if overwriteAuthorizedKeysFile is set to true
authorizedKeysPath = "authorized_keys"

# Whether failure to write out the authorized_keys file will cause a non-zero exit code
# Be careful with this! If key validation was successful but the file fails, login will
# be denied by OpenSSH!
raiseAuthorizedKeysErrors = false
