# Record to query for AKD/S data
recordName = "_akds.example.com"

# Public key to verify AKDS signatures against
pubkey = """
----- BEGIN PGP PUBLIC KEY BLOCK -----
...
----- END PGP PUBLIC KEY BLOCK -----
"""

# Whether to accept data from an AKDS record if it fails verification
# Missing signatures on AKDS records will always produce an error
acceptUnverified = false
