# Record to query for AKD/S data
recordName = "_akds.example.com"

# Public key to verify AKDS signatures against
pubkey = """
----- BEGIN PGP PUBLIC KEY BLOCK -----
...
----- END PGP PUBLIC KEY BLOCK -----
"""

# Whether to accept data from an AKDS record if it fails verification
# Note that this will in essence treat all records as AKD records. Failed or
# missing signatures on AKDS records will produce a warning instead of an error.
acceptUnverified = false
