# Record to query for AKD/S data
recordName = "_akds.example.com"

# Public key to verify AKDS signatures against
pubkey = """
----- BEGIN PGP PUBLIC KEY BLOCK -----
...
----- END PGP PUBLIC KEY BLOCK -----
"""

# Whether to accept data from an AKDS record if it fails verification
# Missing signatures on AKDS records will always produce an error
acceptUnverified = false

# Whether to overwrite authorized_keys with AKD/S results
overwriteAuthorizedKeys = false

# Path to authorized_keys
# Relative paths are relative to this config file
# Only applies if overwriteAuthorizedKeysFile is set to true
authorizedKeysPath = "authorized_keys"
