on: [push, pull_request]
name: Build akd-client
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    
    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
        
    - name: Restore package cache
      uses: actions/cache@v2
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        # * Build cache (Mac)
        # * Build cache (Windows)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: linux-go-1.18.x-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          linux-go-1.18.x-

    - name: Build akd-client 
      run: go build
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.3
      with:
          name: akd-client
          path: akd-client
